/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}
group = "eichinger.peter.taxi"
version = "0.0.1"
//ext {
//
//}
repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
//    val  lombokVersion = "1.18.24"
//    constraints {
//        // Define dependency versions as constraints
//        implementation("org.apache.commons:commons-text:1.9")
//    }
    compileOnly ("org.projectlombok:lombok:1.18.24")
    annotationProcessor ("org.projectlombok:lombok:1.18.24")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
